/**
 * Major cities (population ≥ 80 000) grouped by EU country name.
 * Generated from the GeoNames dataset via the all-the-cities npm package,
 * with district entries removed and names standardised to English where a
 * common English form exists (Florence, Rome, Cologne, …).
 * Mirror of `mobile/src/lib/cities.ts` — keep both in sync.
 */
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Austria: [
    'Graz', 'Innsbruck', 'Klagenfurt', 'Linz', 'Salzburg', 'Vienna',
    'Wels',
  ],
  Belgium: [
    'Aalst', 'Antwerp', 'Bruges', 'Brussels', 'Charleroi', 'Genk',
    'Ghent', 'Hasselt', 'Kortrijk', 'La Louvière', 'Leuven', 'Liège',
    'Mechelen', 'Mons', 'Namur', 'Ostend', 'Seraing', 'Sint-Niklaas',
    'Tournai',
  ],
  Czechia: [
    'Brno', 'České Budějovice', 'Havířov', 'Hradec Králové', 'Liberec', 'Olomouc',
    'Ostrava', 'Pardubice', 'Pilsen', 'Prague', 'Ústí nad Labem',
  ],
  Denmark: [
    'Aalborg', 'Aarhus', 'Copenhagen', 'Esbjerg', 'Frederiksberg', 'Odense',
    'Randers',
  ],
  Finland: [
    'Espoo', 'Helsinki', 'Jyväskylä', 'Kuopio', 'Lahti', 'Oulu',
    'Tampere', 'Turku', 'Vantaa',
  ],
  France: [
    'Aix-en-Provence', 'Amiens', 'Angers', 'Argenteuil', 'Asnières-sur-Seine', 'Aulnay-sous-Bois',
    'Avignon', 'Besançon', 'Bordeaux', 'Boulogne-Billancourt', 'Brest', 'Caen',
    'Clermont-Ferrand', 'Colombes', 'Courbevoie', 'Créteil', 'Dijon', 'Grenoble',
    'Le Havre', 'Le Mans', 'Lille', 'Limoges', 'Lyon', 'Marseille',
    'Metz', 'Montpellier', 'Montreuil', 'Mulhouse', 'Nancy', 'Nanterre',
    'Nantes', 'Nice', 'Nîmes', 'Orléans', 'Paris', 'Pau',
    'Perpignan', 'Poitiers', 'Reims', 'Rennes', 'Roubaix', 'Rouen',
    'Saint-Denis', 'Saint-Étienne', 'Strasbourg', 'Toulon', 'Toulouse', 'Tourcoing',
    'Tours', 'Versailles', 'Villeurbanne', 'Vitry-sur-Seine',
  ],
  Germany: [
    'Aachen', 'Augsburg', 'Bergisch Gladbach', 'Berlin', 'Bielefeld', 'Bochum',
    'Bonn', 'Bottrop', 'Braunschweig', 'Bremen', 'Bremerhaven', 'Chemnitz',
    'Cologne', 'Cottbus', 'Darmstadt', 'Dortmund', 'Dresden', 'Duisburg',
    'Düren', 'Düsseldorf', 'Erfurt', 'Erlangen', 'Essen', 'Esslingen',
    'Flensburg', 'Frankfurt', 'Freiburg', 'Fürth', 'Gelsenkirchen', 'Gera',
    'Göttingen', 'Gütersloh', 'Hagen', 'Halle', 'Hamburg', 'Hamm',
    'Hanau', 'Hanover', 'Heidelberg', 'Heilbronn', 'Herne', 'Hildesheim',
    'Ingolstadt', 'Iserlohn', 'Jena', 'Kaiserslautern', 'Karlsruhe', 'Kassel',
    'Kiel', 'Koblenz', 'Konstanz', 'Krefeld', 'Leipzig', 'Leverkusen',
    'Lübeck', 'Ludwigsburg', 'Ludwigshafen am Rhein', 'Lünen', 'Magdeburg', 'Mainz',
    'Mannheim', 'Marl', 'Minden', 'Moers', 'Mönchengladbach', 'Mülheim',
    'Munich', 'Münster', 'Neuss', 'Nuremberg', 'Oberhausen', 'Offenbach',
    'Oldenburg', 'Osnabrück', 'Paderborn', 'Pforzheim', 'Potsdam', 'Ratingen',
    'Recklinghausen', 'Regensburg', 'Remscheid', 'Reutlingen', 'Rostock', 'Saarbrücken',
    'Salzgitter', 'Schwerin', 'Siegen', 'Solingen', 'Stuttgart', 'Trier',
    'Tübingen', 'Ulm', 'Velbert', 'Villingen-Schwenningen', 'Wiesbaden', 'Wilhelmshaven',
    'Witten', 'Wolfsburg', 'Worms', 'Wuppertal', 'Würzburg', 'Zwickau',
  ],
  Greece: [
    'Acharnes', 'Athens', 'Glyfada', 'Heraklion', 'Ilion', 'Kalamaria',
    'Kallithea', 'Larissa', 'Nikaia', 'Patras', 'Peristeri', 'Piraeus',
    'Thessaloniki', 'Volos',
  ],
  Hungary: [
    'Budapest', 'Debrecen', 'Győr', 'Kecskemét', 'Miskolc', 'Nyíregyháza',
    'Pécs', 'Szeged', 'Székesfehérvár',
  ],
  Ireland: [
    'Cork', 'Dublin', 'Galway', 'Limerick', 'Waterford',
  ],
  Italy: [
    'Ancona', 'Andria', 'Bari', 'Barletta', 'Bergamo', 'Bologna',
    'Bolzano', 'Brescia', 'Cagliari', 'Catania', 'Como', 'Ferrara',
    'Florence', 'Foggia', 'Forlì', 'Genoa', 'Giugliano in Campania', 'La Spezia',
    'Lecce', 'Livorno', 'Lucca', 'Messina', 'Mestre', 'Milan',
    'Modena', 'Monza', 'Naples', 'Novara', 'Padua', 'Palermo',
    'Parma', 'Perugia', 'Pescara', 'Piacenza', 'Prato', 'Ravenna',
    'Reggio Calabria', 'Reggio Emilia', 'Rimini', 'Rome', 'Salerno', 'Sassari',
    'Siracusa', 'Taranto', 'Terni', 'Torre del Greco', 'Trento', 'Trieste',
    'Turin', 'Udine', 'Verona', 'Vicenza',
  ],
  Netherlands: [
    "'s-Hertogenbosch", 'Alkmaar', 'Almere', 'Amersfoort', 'Amsterdam', 'Apeldoorn',
    'Arnhem', 'Breda', 'Delft', 'Deventer', 'Dordrecht', 'Eindhoven',
    'Enschede', 'Groningen', 'Haarlem', 'Heerlen', 'Hengelo', 'Hilversum',
    'Hoofddorp', 'Leeuwarden', 'Leiden', 'Maastricht', 'Nijmegen', 'Rotterdam',
    'Tilburg', 'Utrecht', 'Venlo', 'Zaandam', 'Zoetermeer', 'Zwolle',
  ],
  Poland: [
    'Białystok', 'Bielsko-Biała', 'Bydgoszcz', 'Bytom', 'Chorzów', 'Częstochowa',
    'Dąbrowa Górnicza', 'Elbląg', 'Gdańsk', 'Gdynia', 'Gliwice', 'Gorzów Wielkopolski',
    'Grudziądz', 'Jastrzębie-Zdrój', 'Jaworzno', 'Jelenia Góra', 'Kalisz', 'Katowice',
    'Kielce', 'Konin', 'Koszalin', 'Kraków', 'Legnica', 'Łódź',
    'Lublin', 'Nowy Sącz', 'Olsztyn', 'Opole', 'Piotrków Trybunalski', 'Płock',
    'Poznań', 'Radom', 'Ruda Śląska', 'Rybnik', 'Rzeszów', 'Słupsk',
    'Sosnowiec', 'Szczecin', 'Tarnów', 'Toruń', 'Tychy', 'Wałbrzych',
    'Warsaw', 'Włocławek', 'Wrocław', 'Zabrze', 'Zielona Góra',
  ],
  Portugal: [
    'Amadora', 'Aveiro', 'Braga', 'Coimbra', 'Faro', 'Funchal',
    'Guimarães', 'Leiria', 'Lisbon', 'Matosinhos', 'Odivelas', 'Porto',
    'Setúbal', 'Sintra', 'Vila Nova de Gaia', 'Viseu',
  ],
  Romania: [
    'Alba Iulia', 'Arad', 'Bacău', 'Baia Mare', 'Bistrița', 'Botoșani',
    'Brăila', 'Brașov', 'Bucharest', 'Buzău', 'Cluj-Napoca', 'Constanța',
    'Craiova', 'Deva', 'Drobeta-Turnu Severin', 'Focșani', 'Galați', 'Giurgiu',
    'Iași', 'Oradea', 'Piatra Neamț', 'Pitești', 'Ploiești', 'Râmnicu Vâlcea',
    'Reșița', 'Roman', 'Satu Mare', 'Sfântu Gheorghe', 'Sibiu', 'Slatina',
    'Suceava', 'Târgoviște', 'Târgu Jiu', 'Târgu Mureș', 'Timișoara', 'Tulcea',
    'Vaslui', 'Zalău',
  ],
  Spain: [
    'A Coruña', 'Albacete', 'Alcalá de Henares', 'Alcobendas', 'Alcorcón', 'Algeciras',
    'Alicante', 'Almería', 'Avilés', 'Badajoz', 'Badalona', 'Barakaldo',
    'Barcelona', 'Bilbao', 'Burgos', 'Cáceres', 'Cádiz', 'Cartagena',
    'Castellón de la Plana', 'Córdoba', 'Cornellà de Llobregat', 'Coslada', 'Dos Hermanas', 'El Ejido',
    'El Puerto de Santa María', 'Elche', 'Fuenlabrada', 'Gandia', 'Getafe', 'Getxo',
    'Gijón', 'Girona', 'Granada', 'Guadalajara', 'Huelva', 'Jaén',
    'Jerez de la Frontera', "L'Hospitalet de Llobregat", 'La Laguna', 'Las Palmas de Gran Canaria', 'Las Rozas de Madrid', 'Leganés',
    'León', 'Lleida', 'Logroño', 'Lorca', 'Lugo', 'Madrid',
    'Málaga', 'Marbella', 'Mataró', 'Móstoles', 'Murcia', 'Orihuela',
    'Ourense', 'Oviedo', 'Palencia', 'Palma', 'Pamplona', 'Parla',
    'Pontevedra', 'Pozuelo de Alarcón', 'Reus', 'Roquetas de Mar', 'Sabadell', 'Salamanca',
    'San Fernando', 'San Sebastián', 'Sant Boi de Llobregat', 'Santa Coloma de Gramenet', 'Santa Cruz de Tenerife', 'Santander',
    'Santiago de Compostela', 'Seville', 'Talavera de la Reina', 'Tarragona', 'Telde', 'Terrassa',
    'Toledo', 'Torrejón de Ardoz', 'Torrevieja', 'Valencia', 'Valladolid', 'Vigo',
    'Vitoria-Gasteiz', 'Zaragoza',
  ],
  Sweden: [
    'Borås', 'Eskilstuna', 'Gävle', 'Gothenburg', 'Halmstad', 'Helsingborg',
    'Huddinge', 'Jönköping', 'Karlstad', 'Linköping', 'Lund', 'Malmö',
    'Norrköping', 'Örebro', 'Södertälje', 'Sollentuna', 'Stockholm', 'Umeå',
    'Uppsala', 'Västerås',
  ],
};
